### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by shaunkawano** [BoltsFramework/Bolts-Android#103]
Although `bolts.Task.TaskCompletionSource` is now deprecated on the newest release version, if you follow the way the README tells you to declare it using the older version of the library, it makes IDE warn you just like the screenshot below. (using bolts version 1.1.2.)

![tcs](https://i.gyazo.com/11457fda1dc4fa72f2b051ffab0592e8.png)

I will use the latest version of the library so it is not a huge problem for me, but I guess README either needs to state what classes are deprecated from now on, or temporarily explain how to declare `tcs` with the newest version of the library and maybe with older versions as well?

**Comment by shaunkawano** [comment]
It seems the README is not updated and telling you how to use the latest version of the library, I will make a pull request as a makeshift measure if it's applicable.

**Comment by grantland** [comment]
Fixed via #107
