### ISSUE TITLE
Block of code passed to continueWithTask never gets executed

### ISSUE THREAD

**Issue by alexblack** [BoltsFramework/Bolts-Android#115]
I've got a small set of users who are encountering and issue where ParseUser.fetchInBackground() appears to never call the subsequent code block passed to continueWithTask.  (I realize thats a Parse method, but I think this is Bolts related).

My code looks like this:

```
  public static Task<Void> check() {
    final Task<Void> timeout = Async.delay(timeoutMs);
    final Task<Void> checkUser = checkUser();

    final ArrayList<Task<?>> tasks = new ArrayList<>();
    tasks.add(timeout);
    tasks.add(checkUser);

    return Task.whenAny(tasks).continueWithTask(new Continuation<Task<?>, Task<SubscriptionCheckerResult>>() {
      @Override
      public Task<SubscriptionCheckerResult> then(Task<Task<?>> wrapperTask) throws Exception {
         // ...
      }
    }, Task.BACKGROUND_EXECUTOR);
  }

  public static Task<Void> checkUser() {
    final ParseUser user = ParseUser.getCurrentUser();
    return user.fetchInBackground().onSuccessTask(new Continuation<ParseObject, Task<Void>>() {
      @Override
      public Task<Void> then(Task<ParseObject> task) throws Exception {
         // ...   
      }
    }, Task.BACKGROUND_EXECUTOR);
  }
```

And for a small percentage of users the code seems to never return from user.fetchInBackground.  

(Related: a number of months back I adopted the practice of always specifying an executor, and changed a bunch of code to use the BACKGROUND_EXECUTOR, and caused a similar issue, and was unable to figure it out, so I reverted the change).

I've also added code which in the case of a timeout, adds a `.continueWith` call to the checkUser variable, and logs when it ultimately fails or succeeds, and in most cases it doesn't do either.

**Comment by grantland** [comment]
Could you elaborate on how you think this code might be causing a deadlock?

**Comment by alexblack** [comment]
I don't have any theories! I just have exceptions logged where the code is timing out, and log captures showing the last line of code run is one before user.fetchInBackground.

**Comment by grantland** [comment]
Unfortunately with this limited information I don't see anything actionable for this issue, so I'll be closing this for now. Feel free to reopen if you have any additional information to add that could point to an issue in Bolts.
