### ISSUE TITLE
Does anyone have a demo project available?

### ISSUE THREAD

**Issue by roblav96** [BoltsFramework/Bolts-Android#125]
I'm trying to play around with `Bolts-Android` and it would be very helpful if someone could direct me towards a demo or a project that uses `Bolts-Android`.

Thank you! :D

**Comment by roblav96** [comment]
Bump? :/

**Comment by madibalive** [comment]
Hi , am currently using bolts , i would published a how to guide soon , after i finish my project  it would be best way to implement this feature using bolts , i absolutely love this library as it easier than RXJAVA

**Comment by grantland** [comment]
We don't have a good demo project outside of the examples in the README, but Parse-SDK-Android utilizes Bolts and you can check out the source code: https://github.com/ParsePlatform/Parse-SDK-Android

**Comment by roblav96** [comment]
Ah just what I'm looking for! thanks!
