### ISSUE TITLE
Put the code to open

### ISSUE THREAD

**Issue by Christopherbur** [BoltsFramework/Bolts-Android#144]
https://github.com/BoltsFramework/Bolts-Android/blob/630ead0230af434f3943e2c41becbf3d6872fbb7/bolts-tasks/src/main/java/bolts/CancellationTokenSource.java#L211

**Comment by grantland** [comment]
Could you please elaborate?

**Comment by Christopherbur** [comment]
144

**Comment by grantland** [comment]
`CancellationTokenSource` objects are one time use
