### ISSUE TITLE
Update to MIT license

### ISSUE THREAD

**Issue by iyegoroff** [BoltsFramework/Bolts-Android#149]
Please relicense this project to MIT - it is being used by Fresco & React-Native, whose licenses have already been changed from BSD + PATENTS to MIT.

Original issues:
https://github.com/facebook/fresco/issues/2242
https://github.com/facebook/react-native/issues/22260

**Comment by JoelMarcey** [comment]
Bolts-Android has been relicensed to MIT 👍

**Comment by iyegoroff** [comment]
Thanks! Can you also relicense Bolts-ObjC to MIT?
