### ISSUE TITLE
Get task from TaskCompletionSource without executing it.

### ISSUE THREAD

**Issue by omkar-tenkale** [BoltsFramework/Bolts-Android#161]
I'm trying to achieve a particular functionality where
User sees a list of downloads running.
Initially all downloads are pending.
The tasks are stored in arraylist to be used by recyclerview.
The first task starts running and others are pending.
All tasks are chanined one after another with `continueWithTask()`  method 

So expected result is after user clicks some button, first task starts running
After it completes second task starts running and so on till all tasks are completed.

I can achieve this using a method like 

 ```
 ArrayList<Task<String>> tasklist;
        public void chainDownloads(){

            for (int i = 0; i < tasklist.size(); i++) {
                int j = i;
                tasklist.get(j).continueWithTask(new Continuation<String, Task<String>>() {
                    @Override
                    public Task<String> then(Task<String> task) throws Exception {
                        return tasklist.get(j+1);
                    }
                });
            }
        }




  private void createDownloadTask() {
            source  = new TaskCompletionSource<String>();

            mTask = source.getTask();
        }

```

But if user clicks on some item in recycler view while the chain is progressing,i want to start that task immediately.
So a task can either be started by previous task in chain or at any time by user click.
The above code handles chained execution but i don't know how can i implement force start mechanism on it.

One way is to wrap the task with an object and when item is clicked in recyclerview get the wrapper object, then get the task and somehow execute it.

But if a wrapper object is made like this

 ```
public class DownlaodTaskWrapper {
        Task<String> mTask;
         TaskCompletionSource<String> source;

        public void getTask(){
            if(mTask==null){
                createTask();
            }
             return mtask;
        }

        public void execute(){
            if(mTask==null){  createTask(); }
            String result = "one"+"7"; // do some work
            source.setResult(result);
        }

        ` private void createTask() {
            source  = new TaskCompletionSource<String>();
            mTask = source.getTask();
        }
}
```

Here i can call execute() when user performs click.
But then i dont know how will the task be executed when it is called by its previous task in chain?
For that i need to  write code in createTask() but then the code will be executed when i chain all tasks in for loop even before user click anything.

Could this be solved with bolts properly?

**Comment by grantland** [comment]
Issues are more of a place to discuss issues or bugs in the library, so I'll be closing this for now. In the future it's probably best to post on Stackoverflow or something similar.

I'm not sure if I'm understanding your problem, but from what I can tell your solution should or work you're at least pretty close. Here's a simple solution that might make things clearer:

```
public class DownloadManager {

  // The TCS is the trigger since any Download enqueued will be continued off it's Task
  public TaskCompletionSource<Void> mExecuteAllTcs;
  public Task<Void> mLastDownloadTask;

  // Map of TCS triggers for individual downloads
  public Map<String, TaskCompletionSource<Void>> mIdToExecuteTcs = new HashMap<>();

  public void enqueue(Download download) {
    Task<Void> downloadTask = downloadAsync(download);

    // Init queue if in the cleared state
    if (mExecuteAllTcs == null) {
      mExecuteAllTcs = new TaskCompletionSource<>();
      mLastDownloadTask = mExecuteAllTcs.getTask();
    }
    // Chain the download upon the completion of the last Task in the queue
    mLastDownloadTask = mLastDownloadTask.continueWithTask((resultTask) -> {
      // Tasks will only be run once, so if this downloadTask was completed outside the queue, 
      // it'll basically no-op and go onto the next one.
      return downloadTask;
    };

    // Create a new trigger for this download and add it to our Map
    TaskCompletionSource<Void> executeTcs = new TaskCompletionSource<>();
    mExecuteDownloadTcs.getTask().continueWithTask((resultTask) -> {
      return downloadTask;
    };
    mIdToDownloadTask.put(download.getId(), executeTcs);
  }

  public executeAll() {
    mExecuteAllTcs.setResult(null);

    // Clear queue
    mExecuteAllTcs = null;
    mLastDownloadTask = null;
  }

  public void execute(String id) {
    if (mIdToExecuteTcs.contains(id)) {
      mIdToExecuteTcs.remove(id).setResult(null);
    }
  }
}
```

**Comment by omkar-tenkale** [comment]
Thanks for the quick response.
The reason i open issues here is because the library guide is though helpful **not** sufficient.
I wasn't able to find a single guide to bolts on internet except its own README
I had to browse through issues for a hello world example and  i did actually find one.
Creating issues for obvious doubts will help many to understand and use bolts faster.

These are my conclusions from above code.Please correct me if i'm wrong
1. executeAll() method will not really start executing all tasks but it will start the chain so next download will start after first one finishes. 

2. To really execute all concurrently i have to loop through hashmap and call execute(String id) 

3. If i call execute() with some id, the task will start and it will be removed from list but it's still chained    so what will happen when the chain reaches an already completed task.I guess it automatically continues next or do i have to add manual checks?

**Comment by grantland** [comment]
The best bet would be to take a look at Microsoft's Task Parallel Library (TPL) docs as this was mainly based off that: https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl

There are a few minor differences, but for the most part it's pretty close.

> 1. executeAll() method will not really start executing all tasks but it will start the chain so next download will start after first one finishes.

Correct. A better name for `executeAll()` would be `startExecutingSerially()`.

> 2. To really execute all concurrently i have to loop through hashmap and call execute(String id)

In my example, yes. You didn't really ask about this functionality, so I didn't include it.

> 3. If i call execute() with some id, the task will start and it will be removed from list but it's still chained so what will happen when the chain reaches an already completed task.I guess it automatically continues next or do i have to add manual checks?

This is explained in my example:

```
      // Tasks will only be run once, so if this downloadTask was completed outside the queue, 
      // it'll basically no-op and go onto the next one.
```
