### ISSUE TITLE
How not to start a task when creating it?

### ISSUE THREAD

**Issue by omkar-tenkale** [BoltsFramework/Bolts-Android#162]
This is the example given in guide

public Task<String> succeedAsync() {
  TaskCompletionSource<String> successful = new TaskCompletionSource<>();
  successful.setResult("The good result.");
  return successful.getTask();
}

which returns a task

I can chain this task with another task by continewith method.
**But the problem is that when i create this task and return it , i also execute it at the same time.**

This is something i dont want to happen.

For example, 
this is my task.
```

 private Task<Void> processAsync(ListItem item,int finalI) {
        TaskCompletionSource tcs = new TaskCompletionSource();
         Task.callInBackground(new Callable<Void>() {
            @Override
            public Void call() throws Exception {
                    //This too is executed when returning task.
                     //Expected result is this should be called when task.setresult() is executed on previous                      task to which this task was chained

               }
        });
        return tcs.getTask();

    }
```

How can i return a task without triggering its main operation.
And trigger this task later by othertask.setresult()
when othertask.continuewithtask(thistask)
is done before

**Comment by grantland** [comment]
Closing since this is not an actual issue. Please use Stackoverflow or something similar for future questions.

`Task`s in Bolts are always "hot", which means they run upon creation. You can chain the asynchronous work that you don't want to start off a `TaskCompletionSource` which you can resolve when you want the asynchronous work to run.
