### ISSUE TITLE
JetBrains kotlin problems

### ISSUE THREAD

**Issue by romansl** [BoltsFramework/Bolts-Android#40]
Tris simple code does not work in [kotlin](http://kotlinlang.org/) language

    Task.create<String>().setResult("ggg")

IDE says:

    Type mismatch.
    Required: TResult 
    Found: kotlin.String

May be you should declare TaskCompletionSource as non-internal class?

**Comment by grantland** [comment]
Unfortunately, I'm not too familiar with kotlin. Are you sure that `TaskCompletionSource` being an internal class is the problem? 

Are you able to initialize `TaskCompletionSource` on it's own like the following?

```
Task<String>.TaskCompletionSource tcs = Task.create();
tcs.setResult("ggg");
```

(This is in Java as I'm unfamiliar with Kotlin syntax)

Additionally, `TaskCompletionSource` needs to modify the internals of `Task`, so it'd require a huge amount of refactoring to make it a non-internal class.

**Comment by romansl** [comment]
I made TaskCompletionSource static and its works fine now.

Check out here: https://github.com/romansl/Bolts-Android/blob/989541b7492452189da34a3277284778fbba6616/Bolts/src/bolts/Task.java#L502

**Comment by JosephEarl** [comment]
Would be a breaking change

**Comment by grantland** [comment]
Could this be a bug in Kotlin that has been fixed since?

**Comment by andrewtoth** [comment]
This is actually not a bug with Kotlin, it is by design. You can read here http://blog.jetbrains.com/kotlin/2015/04/upcoming-changes-and-more/.

>When a generic class Outer has an inner class Inner, Java allows us to use generic parameters of Outer inside Inner:

>Although very logical, this feature also has rather few use cases, and current implementation we have in Kotlin requires a lot of work before it is production quality. So, we are going to forbid this, and maybe implement it in later releases of Kotlin.

**Comment by andrewtoth** [comment]
A good workaround I have found is to write an extension in Kotlin for TaskCompletionSource like so:

```
fun <T> Task.TaskCompletionSource.setResult(result: T) {
    Util.setResult(this, result)
}
```

where Util is a class with static method that takes the TaskCompletionSource and the result is class Object:

```
    public static void setResult(Task.TaskCompletionSource tcs, Object result) {
        tcs.setResult(result);
    }
```

**Comment by grantland** [comment]
Can someone check if #84 fixes the Kotlin problems?

**Comment by andrewtoth** [comment]
I can confirm #84 fixes the problem with Kotlin.

**Comment by grantland** [comment]
Awesome, thanks!
