### ISSUE TITLE
How to stop

### ISSUE THREAD

**Issue by yanglinglong1** [BoltsFramework/Bolts-Android#41]
I use Boits  run asyncMethod  like this
```java
Task.callInBackground(new Callable<AuthData>() {
			@Override
			public AuthData call() throws Exception {
				// TODO  network   do  login 
				AuthData data = new AuthData("121212", "23423423");
				Thread.sleep(5000);
				return data;
			}
		}).onSuccess(new Continuation<AuthData, String>() {
			@Override
			public String then(Task<AuthData> result) throws Exception {
				// TODO something other	
				return "success";
			}
		});
```
But if I dropped out of Activity or want to stop task, what should I do

**Comment by grantland** [comment]
Closing for now, feel free to reopen if you have any more questions!

**Comment by ljfkira** [comment]
What will happen to the tasks if I stop the launching activity.
Will they still running until finished?
If one of those tasks is fetching data from some server, what happen to the progress?

**Comment by grantland** [comment]
The Task will continue to run.
