### ISSUE TITLE
Separate Bolts into 2 Modules for Tasks and AppLinks

### ISSUE THREAD

**Issue by JosephEarl** [BoltsFramework/Bolts-Android#49]
I'd like to use the Task pattern in projects where I don't need AppLinks.

e.g. split Bolts into 2 modules:

    Bolts/Tasks
    Bolts/AppLinks // Depends on Tasks

Publish Bolts/AppLinks with the same Maven identifiers as currently used.

If desired AppLinks could further be split, into a part which does not rely on tasks and another that does:

    Bolts/AppLinks
    Bolts/Tasks
    Bolts/AppLinksTasks // Depends on Tasks and AppLinks

With Bolts/AppLinks containing the core model, and Bolts/AppLinksTasks (or Bolts/AppLinksResolver).
Publish Bolts/AppLinksTasks with the same Maven identifiers as currently used.

If you're open to the idea I can submit a PR.

**Comment by ChaitanyaPramod** [comment]
Completely agree with the evaluation. I too believe that Bolts/Tasks is a complete module by itself, and should be broken off from AppLinks

**Comment by grantland** [comment]
right now we're under bolts-android. would anyone have issues to moving Tasks to bolts-tasks and AppLinks to bolts-applinks as opposed to bolts-android-tasks and bolts-android-applinks? bolts-android could still be the umbrella for both Tasks and AppLinks.

**Comment by JosephEarl** [comment]
Sounds fine to me

**Comment by skyfishjy** [comment]
expect！

**Comment by grantland** [comment]
@JosephEarl @ChaitanyaPramod @skyfishjy Please take a look at #90
