### ISSUE TITLE
confusion with creating of async methods

### ISSUE THREAD

**Issue by rhussel** [BoltsFramework/Bolts-Android#52]
public Task<Void> fetchAsync(ParseObject obj) {
        final Task<ParseObject>.TaskCompletionSource tcs = Task.create();
        obj.fetchInBackground(new GetCallback() {
            public void done(ParseObject object, ParseException e) {
                if (e == null) {
                    tcs.setResult(object);
                } else {
                    tcs.setError(e);
                }
            }
        });
        return tcs.getTask();
    }

i'm a bit confused with this code.. how come the tcs is type of Task<ParseObject> can be used as return type for the method with return type of Task<Void>...i also tried to run this part of code..and it gives me incompatible types error..any explanation will be much appreciated. thanks :)

**Comment by aclassen** [comment]
Your function should return a Task fo type T.
Also the type of your TaskCompletionSource must be the same type.

public Task<ParseObject> fetchAsync(ParseObject obj) {
final Task<ParseObject>.TaskCompletionSource tcs = Task.create();
obj.fetchInBackground(new GetCallback() {
public void done(ParseObject object, ParseException e) {
if (e == null) {
tcs.setResult(object);
} else {
tcs.setError(e);
}
}
});
return tcs.getTask();
}

**Comment by rhussel** [comment]
yeah   :) 
im just confused with the documentation in readme

public Task<Void> fetchAsync(ParseObject obj) {
  final Task<ParseObject>.TaskCompletionSource tcs = Task.create();
  obj.fetchInBackground(new GetCallback() {
    public void done(ParseObject object, ParseException e) {
     if (e == null) {
       tcs.setResult(object);
     } else {
       tcs.setError(e);
     }
   }
  });
  return tcs.getTask();
}

i understand this late..few minutes after i post this issue..thanks

**Comment by aclassen** [comment]
np

**Comment by grantland** [comment]
Sorry about the typo, I've just committed a fix. Thanks!
