### ISSUE TITLE
How do I invoke a task on an executor?

### ISSUE THREAD

**Issue by alexblack** [BoltsFramework/Bolts-Android#78]
If I have some function like this:

```Task<Void> doAsync() { // do stuff  }}```

How do I execute it on an executor?  I tried using Call:

```
return Task.Call(new Callable<Void>() {
      public Void call() throws Exception {
         return doAsync();
     }
});
```

but obviously that doesn't work, the return type of Call is Task<Void> (what I want), but the return type of Callable is Void (not Task<Void>).

Thanks!  Alex

**Comment by grantland** [comment]
As a caller, you generally wouldn't specify what executor a method such as `doAsync()` will execute on, since the caller shouldn't care or depend on which executor it's executing on.

If you're asking how to execute a `Task` on a specific executor, we have docs [here](https://github.com/BoltsFramework/Bolts-Android#task-executors).

**Comment by alexblack** [comment]
Hi Grant, hmm, now I'm confused :)

1. I am for some reason specifying an executor, and caring which executor it executes on .  This is Android code, so I don't want to execute the method on the UI thread.  Am I going about this the wrong way?

2. Hmm, I am asking how to execute a task on a specific executor, I've read those exact docs, couldn't figure out how, so I asked this question.

**Comment by grantland** [comment]
If you're composing the `Task`:

```java
Executor executor = // ...
Task<Void> task = Task.call(() -> {
  // some long running task
}, executor);
// or
Task<Void> task = Task.forResult(null).continueWithTask((t) -> {
  // some long running task
}, executor);
```

If you're calling an async method such as `doAsync()`, the best practices would be to let `doAsync()` execute on whatever executor it was designed to be executed on and once it returns control you can stay on that executor or switch to a different one.

**Comment by alexblack** [comment]
Ok, that makes some sense. I think I've been doing this all backwards. I've got a number of methods that return Task<T> that are not asynchronous, instead they are just composable into an already asynchronous chain.

It sounds like all methods that return Task<T> should already be asychronous...?   Also, what do you think of optionally passing the executor into a method like that, eg

Task<Void> task = doAsync(param1, executor);

**Comment by grantland** [comment]
While it's possible, I wouldn't recommend that unless there's a specific reason you want the executor to be variable and defined by the caller. In most cases the method will have it's executors defined from inception and compiled in.

Here's an example of how we define our asynchronous network requests to be executed on a `NETWORK_EXECUTOR`, parsed on `Task.BACKGROUND_EXECUTOR` and then given control back to it's caller to be continued on whatever executor it wants: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseRequest.java#L188

**Comment by alexblack** [comment]
Great stuff, I like how you can link to an example in the parse SDK now :)  I'm loving Bolts, I've rewritten most of my async code to use it, its made the code much simpler, and made it run a lot better (fewer threads, no more blocking)

**Comment by grantland** [comment]
It's always great to hear that Bolts is making asynchronous development easier for people, glad I could help :smile:
