### ISSUE TITLE
Bolts conflict with Facebook SDK?

### ISSUE THREAD

**Issue by alexblack** [BoltsFramework/Bolts-Android#80]
Hi, I'm trying to add the latest Facebook Android SDK from Gradle:

```
    compile 'com.facebook.android:facebook-android-sdk:4.5.0'
```

And I get this error:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;

Error:Execution failed for task ':app:dexFreeArmeabi-v7aDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by alexblack** [comment]
I got around this:

    compile ('com.facebook.android:facebook-android-sdk:4.5.0') {
        exclude module: 'bolts-android'
    }

The conflict seems to be between Parse SDK (i'm currently a bit behind on 1.9.1) and Facebook SDK.

**Comment by grantland** [comment]
Yeah, the Facebook SDK has a dependency on Bolts and that's the correct workaround. I'll be closing this issue for now, but feel free to comment if you need it to be reopened.

**Comment by yakubpashask** [comment]
Even after mentioning it. i am still getting the below error

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.transform.api.TransformException: java.util.zip.ZipException: duplicate entry: com/parse/AbstractQueryController$1.class

This is my grade dependency code:


dependencies {
    compile fileTree(include: ['*.jar'], exclude: 'android-support-v4.jar',dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile files('libs/Parse-1.10.3.jar')
    compile files('libs/bolts-android-1.2.1.jar')
    compile 'com.android.support:design:23.1.0'
    compile 'com.android.support:cardview-v7:23.1.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.github.satyan:sugar:1.3'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.android.support:recyclerview-v7:23.1.0'
    compile 'com.google.android.gms:play-services-identity:8.1.0'
    compile 'com.google.android.gms:play-services-plus:8.1.0'
    compile 'com.android.support:support-v4:23.1.0'
    compile 'com.google.android.gms:play-services-analytics:8.1.0'
    compile 'com.github.siyamed:android-shape-imageview:0.9.+@aar'
    compile files('libs/org.apache.http.legacy.jar')
    compile ('com.facebook.android:facebook-android-sdk:4.6.0') {
        exclude module: 'bolts-android'
    }

}
Thanks
yakub

**Comment by kamoljan** [comment]
Hi @yakubpashask 

Try to clean and rebuild:

    ./gradlew clean build

also maybe your have duplicated version of Parse in your `libs`.
Try to remove them and use this one instead:

    compile 'com.parse.bolts:bolts-android:1.2.1'
    compile 'com.parse:parse-android:1.10.3'

**Comment by yakubpashask** [comment]
OMG!!! thats awesome .. that's fixed my build issues.
You saved me..Thank you so much @kamoljan .. 

Thanks
Yakub.

**Comment by ygnessin** [comment]
A similar issue to this is back again: The newest version of Facebook SDK (4.8.2) is still using the old `bolts-android`. This causes duplicate class definitions if you are also relying on the newer bolts artifacts, `bolts-tasks` and `bolts-applinks`. In my case, this occurred because I upgraded my Parse SDK to 1.11.0 which uses the new bolts artifacts.

The solution for me was similar to the one from last time: exclude `bolts-android` when compiling Facebook. But you must also explicitly compile the two new artifacts, or else Facebook won't be able to find the classes it needs to work.

```gradle
compile 'com.parse.bolts:bolts-tasks:1.3.0'
compile 'com.parse.bolts:bolts-applinks:1.3.0'

compile('com.facebook.android:facebook-android-sdk:4.8.2') {
    exclude module: 'bolts-android'
}

compile 'com.parse:parse-android:1.11.0'
```

**Comment by yakubpashask** [comment]
Thanks Yuval, i will check this with the new version of sdk's

On Wed, Dec 9, 2015 at 6:16 AM, Yuval Gnessin <notifications@github.com>
wrote:

> A similar issue to this is back again: The newest version of Facebook SDK
> (4.8.2) is still using the old bolts-android. This causes duplicate class
> definitions if you are also relying on the newer bolts artifacts,
> bolts-tasks and bolts-applinks. In my case, this occurred because I
> upgraded my Parse SDK to 1.11.0 which uses the new bolts artifacts.
>
> The solution for me was similar to the one from last time: exclude
> bolts-android when compiling Facebook. But you must also explicitly
> compile the two new artifacts, or else Facebook won't be able to find the
> classes it needs to work.
>
> compile 'com.parse.bolts:bolts-tasks:1.3.0'
> compile 'com.parse.bolts:bolts-applinks:1.3.0'
>
> compile('com.facebook.android:facebook-android-sdk:4.8.2') {
>     exclude module: 'bolts-android'
> }
>
> compile 'com.parse:parse-android:1.11.0'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BoltsFramework/Bolts-Android/issues/80#issuecomment-163070166>
> .
>



-- 
Regards,
Yakub..

**Comment by angelmarrugo** [comment]
try this works for me

    implementation "com.github.parse-community.Parse-SDK-Android:parse:1.24.1"
    implementation ('com.github.parse-community:ParseFacebookUtils-Android:1.14.0'){
            exclude module: 'bolts-android'
        }
