### ISSUE TITLE
Basic Use of This Library in Android Studio

### ISSUE THREAD

**Issue by PGMacDesign** [BoltsFramework/Bolts-Android#81]
I have followed the instructions on the page regarding setting up the compile declarations in Android Studio. Whenever I try to use the sample code listed on the main Readme, all calls with findAsync, saveAsync, and many more are continually popping up with cannot resolve method. 

Is there another dependency this library needs to run?
Is there another step to setup this other than the gradle commands?

**Comment by grantland** [comment]
`findAsync` and `saveAsync` are fictional asynchronous methods, but are similar to `ParseQuery#findInBackground()` and `ParseObject#saveInBackground()` from the [Parse-SDK-Android](https://github.com/ParsePlatform/Parse-SDK-Android).

**Comment by PGMacDesign** [comment]
Gotcha, so to use it then, I have my own Async method (IE class someTask extends AsyncTask <Void, Void, Void> { ...stufff...} and then use the calls by replacing the findAsync in your examples with my someTask?

**Comment by grantland** [comment]
Kind of, but not really. `Task`s do not depend on using `AsyncTask` anywhere, but they can be used together.

The most simple way of using `Task`s to get something off onto a thread:

```java
public Task<Void> doSomethingAsync() {
  return Task.call(() -> {
    // do some long running operations such as network operations
  }, Task.BACKGROUND_EXECUTOR);
};
```

If you want to do something upon completion of the asynchronous work, like you would with callbacks, you use continuations:

```java
doSomethingAsync().continueWithTask((t) -> {
  if (t.isFaulted()) {
    // error case
  } else if (t.isCancelled()) {
    // canceled case
  } else {
    // success case
  }
  return t;
});
```

**Comment by PGMacDesign** [comment]
Ok, I have copied your example here exactly and am getting compiler errors with the doSomethingAsync().continueWithTask((t) call. It reads, "Lambda expressions are not supported at this language level". Is there something I am missing? Is the t a defined variable somewhere? Is there more to your expression but Android Studio cut it off?

**Comment by grantland** [comment]
Sorry I'm using lambda short hand when typing these out.

```java
(t) -> {
  // ...
}
```

can be replaced with

```java
new Continuation<Void, Task<Void>>() {
  @Override public void done(Task<Void> t) {
    // ...
  }
}
```

**Comment by PGMacDesign** [comment]
Gotcha, perfect, that compiles and works just fine. 
Just one more clarification Q for ya, if my goal is to run multiple server requests (Let's say I'm pinging a Rest API like 4 times), would I write 4 separate .continueWithTask((t) connected together? Or embed network calls within the inner-class?

**Comment by grantland** [comment]
That really depends on how you want to architect your API. If you're going to make asynchronous methods for each API call, you can chain them together using `continueWithTask`, but if this is a one off situation you can also have them all in a single `Continuation`.

**Comment by PGMacDesign** [comment]
I appreciate your time and expertise. Thank you for the help!

**Comment by grantland** [comment]
No problem, I'm glad I've been able to clear everything up! Have fun using Bolts :smile:
