### ISSUE TITLE
Return a immutable singleton for `Task.forResult(null)` and `Task.cancelled()`

### ISSUE THREAD

**Issue by grantland** [BoltsFramework/Bolts-Android#82]
Currently each call to `Task.forResult(null)` and `Task.cancelled()` create new instances of `Task` and `TaskCompletionSource`, which are exactly the same for each execution.

These methods can be extremely common in codebases, especially `Task.forResult(null)`, which is used internally in Bolts-Android and Parse-SDK-Android from converting `null` return values in continuations to stubbing non-asynchronous methods with an asynchronous method signature.

We can optimize these calls by reusing the same value and reduce the amount of memory allocated in applications relying on Bolts and we can do this since each return value is equivalent and essentially immutable.

/cc @nlutsenko

**Comment by nlutsenko** [comment]
:+1:

**Comment by grantland** [comment]
We'd also benefit from caching `Task.forResult(true|false)`. Any other additions that would seem beneficial?

**Comment by wangmengyan95** [comment]
Let's do this!!!
