### ISSUE TITLE
Task.whenAll should return AggregateException on multiple cancelled task

### ISSUE THREAD

**Issue by hallucinogen** [BoltsFramework/Bolts-Android#83]
Currently we set the whole `Task.whenAll` result as cancelled when one of the task is cancelled and there's no error https://github.com/BoltsFramework/Bolts-Android/blob/master/Bolts/src/main/java/bolts/Task.java#L474. This is incorrect since when we consider this scenario
1. There're 4 `Task`s in `Task.whenAll`.
2. Two of them are cancelled, two of them succeed.
3. `Task.whenAll` will return cancelled.

The correct result should be an `AggregateException` that contains 2 `TaskCancelledException` or something similar.

**Comment by grantland** [comment]
To clarify, we should be returning a single `CancellationException` if only one has been cancelled and  `AggregateException` containing multiple `CancellationException`s if more than one has been cancelled. This would be similar to how we handle one or more `Exception`s in `Task.whenAll`.

/cc @nlutsenko

**Comment by grantland** [comment]
So it actually looks like we have the same implementation as .NET:

> If any of the supplied tasks completes in a faulted state, the returned task will also complete in a Faulted state, where its exceptions will contain the aggregation of the set of unwrapped exceptions from each of the supplied tasks.
**If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the Canceled state.**
If none of the tasks faulted and none of the tasks were canceled, the resulting task will end in the RanToCompletion state.
If the supplied array/enumerable contains no tasks, the returned task will immediately transition to a RanToCompletion state before it's returned to the caller.

[Source](https://msdn.microsoft.com/en-us/library/hh160384(v=vs.110).aspx)

**Comment by grantland** [comment]
Working as intended
