### ISSUE TITLE
License mismatch between POM and code

### ISSUE THREAD

**Issue by sschuberth** [BoltsFramework/Bolts-Android#94]
At the example of version 1.2.1, [the code](https://github.com/BoltsFramework/Bolts-Android/blob/1.2.1/LICENSE) refers to a 3-clause BSD license. Yet the [POM](http://search.maven.org/#artifactdetails|com.parse.bolts|bolts-android|1.2.1|) says it would be a "BSD 2-Clause License". I believe either one needs to be fixed.

**Comment by grantland** [comment]
Thanks for bringing this to our attention! We'll get it fixed so that the next release will have the correct licensing in the POM.

**Comment by sschuberth** [comment]
@grantland Looks like this was never fixed completely as [bolts-android/build.gradle](https://github.com/BoltsFramework/Bolts-Android/blob/master/bolts-android/build.gradle#L93) still says "BSD 2-Clause License", and so does [the POM for version 1.40](https://search.maven.org/remotecontent?filepath=com/parse/bolts/bolts-android/1.4.0/bolts-android-1.4.0.pom).
